app = 'n8n-green-paper-7978'
primary_region = 'iad'

[build]
  image = "n8nio/n8n"

[env]
  N8N_HOST = "n8n-green-paper-7978.fly.dev"
  N8N_PORT = "5678"
  N8N_PROTOCOL = "https"

  NODE_ENV = "production"

  WEBHOOK_URL = "https://n8n-green-paper-7978.fly.dev/"
  N8N_EDITOR_BASE_URL = "https://n8n-green-paper-7978.fly.dev"

  GENERIC_TIMEZONE = "America/Bogota"

[http_service]
  internal_port = 5678
  force_https = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
