# fly.toml app configuration file generated for n8n-green-paper-7978 on 2025-12-27T16:49:17-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'n8n-green-paper-7978'
primary_region = 'iad'

[build]
  image = 'n8nio/n8n:latest'

[env]
  GENERIC_TIMEZONE = 'America/Bogota'
  N8N_BASIC_AUTH_ACTIVE = 'false'
  N8N_HOST = 'n8n-green-paper-7978.fly.dev'
  N8N_PORT = '5678'
  N8N_PROTOCOL = 'https'
  WEBHOOK_URL = 'https://n8n-green-paper-7978.fly.dev'

[[mounts]]
  source = 'n8n_data'
  destination = '/home/node/.n8n'

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
